server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    redirect-context-root: false
  address: 0.0.0.0

spring:
  application:
    name: gateway
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: news
          uri: lb://news
          predicates:
            - Path=/news/**
          filters:
            - RewritePath=/news(?<segment>/?.*), /news$\{segment}

        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user(?<segment>/?.*), /user$\{segment}