server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    redirect-context-root: false
  address: 0.0.0.0

spring:
  application:
    name: gateway
  cloud:
    sentinel:
      filter:
        enabled: false
      transport:
        port: 9993
        dashboard: 127.0.0.1:9999
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: false
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0

jwt.secret: kangaroo

ds.gateway.uri: r2dbc:mysql://root:123456@127.0.0.1/gateway
ds.user.uri: r2dbc:mysql://root:123456@127.0.0.1/user

logging:
  level:
    io:
      r2dbc: DEBUG