server:
  port: 8088
  servlet:
    context-path: /cas
  tomcat:
    redirect-context-root: false
  address: 0.0.0.0

spring:
  application:
    name: cas
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/cas?serverTimezone=UTC


# Monitor all requests *
management:
  endpoints:
    web:
      exposure:
        include: '*'

#mybatis plus
mybatis-plus:
  mapper-locations: classpath*:/mappers/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    map-underscore-to-camel-case: true

#http://127.0.0.1:8088/cas/swagger-ui/index.html
springdoc:
  swagger-ui:
    enabled: true

#http://127.0.0.1:8088/cas/doc.html
knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-dynamic-parameter: true